trigger:
- appservice

variables:
  azureSubscription: 'AzureServiceConnection'   # Your Azure DevOps Service Connection name
  webAppName: 'my-nodejs-appservice'       # Your Azure App Service name

jobs:
- job: BuildAndDeploy
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.11.0'   # Or your Node version
    displayName: 'Use Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(webAppName).zip'
      verbose: true
    displayName: 'Archive app files'

  - publish: '$(Build.ArtifactStagingDirectory)/$(webAppName).zip'
    artifact: drop

  - task: AzureWebApp@1
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(webAppName)
      package: '$(Build.ArtifactStagingDirectory)/$(webAppName).zip'
    displayName: 'Deploy Node.js app to Azure App Service'

  - script: |
      echo "Running DB migrations..."
      npm run setup-db
    displayName: 'Run DB migrations'
    env:
      DB_USER: $(DB_USER)
      DB_PASSWORD: $(DB_PASSWORD)
      DB_NAME: $(DB_NAME)
      DB_HOST: $(DB_HOST)
      DB_PORT: $(DB_PORT)
    workingDirectory: '$(System.DefaultWorkingDirectory)'
