trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'myapp'
  registry: 'myregistry.azurecr.io'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  inputs:
    containerRegistry: '<your-service-connection-name>'
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '<your-azure-subscription>'
    azureResourceGroup: '<your-resource-group>'
    kubernetesCluster: '<your-aks-cluster>'
    namespace: 'default'
    command: apply
    useConfigurationFile: true
    configuration: 'manifests/deployment.yml'
