trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'myapp'
  registry: 'cicdbgregistry.azurecr.io'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acr-dev-connection'
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'AZ_LEARN_ONE'
    azureResourceGroup: 'RG_LEARN_ONE>'
    kubernetesCluster: '<your-aks-cluster>'
    namespace: 'default'
    command: apply
    useConfigurationFile: true
    configuration: 'manifests/deployment.yml'
