apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: beneren10/node-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: POSTGRES_DB
            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: SECRET_TOKEN
                  key: SECRET_TOKEN
            - name: BCRYPT_SALT_ROUNDS
              valueFrom:
                secretKeyRef:
                  name: BCRYPT_SALT_ROUNDS
                  key: BCRYPT_SALT_ROUNDS

---
apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 3000          # Public port
      targetPort: 3000  # Container port your app listens on
  type: LoadBalancer

