apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-client
  template:
    metadata:
      labels:
        app: node-client
    spec:
      containers:
        - name: node-client
          image: beneren10/node-client:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-client-service
spec:
  selector:
    app: node-client
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
