apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  setup.sql: |
    DROP TABLE IF EXISTS diary;
    DROP TABLE IF EXISTS user_account;

    CREATE TABLE user_account (
        user_id INT GENERATED ALWAYS AS IDENTITY,
        email VARCHAR(30) UNIQUE NOT NULL,
        password CHAR(60) NOT NULL,
        name VARCHAR(30) NOT NULL,
        PRIMARY KEY (user_id)
    );

    CREATE TABLE diary (
        id INT GENERATED ALWAYS AS IDENTITY,
        category VARCHAR(50) NOT NULL,
        text TEXT NOT NULL,
        title VARCHAR(50) NOT NULL,
        date DATE DEFAULT CURRENT_DATE,
        rating INT NOT NULL DEFAULT=5,
        FOREIGN KEY (user_id) REFERENCES user_account(user_id) ON DELETE CASCADE 
    );
