apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: hyar1nyxg
  POSTGRES_DB: your_db
  BCRYPT_SALT_ROUNDS: 10
  SECRET_TOKEN: 11a129d278e863da8f8f44e9f3a5f61c0aac39176bd0dbcb85c335e0cb94b63f2f2924030ed35c721f82e26cc0ac99d25a16824a5ec44fcf2fe7f62530d67de1
